const now = Date.now();
const hour = 60 * 60 * 1000;

export const MOCK_NOTIFICATIONS = [
  {
    id: "1",
    notification_type: "Placement",
    title: "Microsoft Campus Drive 2026",
    message: "Applications open for Microsoft SDE roles. Deadline: 25 May 2026.",
    created_at: new Date(now - 2 * hour).toISOString(),
    is_read: false,
  },
  {
    id: "2",
    notification_type: "Result",
    title: "Semester 6 Results Published",
    message: "Results for Semester 6 are now available on the student portal.",
    created_at: new Date(now - 5 * hour).toISOString(),
    is_read: false,
  },
  {
    id: "3",
    notification_type: "Event",
    title: "Tech Fest 2026 – Registration",
    message: "Register for workshops and hackathons before slots fill up.",
    created_at: new Date(now - 8 * hour).toISOString(),
    is_read: true,
  },
  {
    id: "4",
    notification_type: "Placement",
    title: "Amazon OA Schedule",
    message: "Online assessment window opens Monday 9:00 AM IST.",
    created_at: new Date(now - 12 * hour).toISOString(),
    is_read: false,
  },
  {
    id: "5",
    notification_type: "Result",
    title: "Re-evaluation Form Deadline",
    message: "Submit re-evaluation requests by 30 May 2026.",
    created_at: new Date(now - 20 * hour).toISOString(),
    is_read: false,
  },
  {
    id: "6",
    notification_type: "Event",
    title: "Guest Lecture: Food Safety",
    message: "CFTRI auditorium, Block A — 2:00 PM this Friday.",
    created_at: new Date(now - 26 * hour).toISOString(),
    is_read: true,
  },
  {
    id: "7",
    notification_type: "Placement",
    title: "Infosys Pre-Placement Talk",
    message: "Mandatory session for eligible CSE and ECE students.",
    created_at: new Date(now - 30 * hour).toISOString(),
    is_read: false,
  },
  {
    id: "8",
    notification_type: "Result",
    title: "Backlog Exam Timetable",
    message: "Summer backlog examination schedule released.",
    created_at: new Date(now - 40 * hour).toISOString(),
    is_read: true,
  },
  {
    id: "9",
    notification_type: "Event",
    title: "Sports Day Registration",
    message: "Team registrations close on 22 May 2026.",
    created_at: new Date(now - 48 * hour).toISOString(),
    is_read: false,
  },
  {
    id: "10",
    notification_type: "Placement",
    title: "TCS Ninja Drive",
    message: "Eligible students must complete profile verification today.",
    created_at: new Date(now - 52 * hour).toISOString(),
    is_read: false,
  },
  {
    id: "11",
    notification_type: "Result",
    title: "Grade Card Download",
    message: "Provisional grade cards are available for download.",
    created_at: new Date(now - 60 * hour).toISOString(),
    is_read: false,
  },
  {
    id: "12",
    notification_type: "Event",
    title: "Library Extended Hours",
    message: "Central library open until 10 PM during exam week.",
    created_at: new Date(now - 72 * hour).toISOString(),
    is_read: true,
  },
];
